"use strict";
//////////////////////////////////////////////////
//////////////     TYPE DEFINITION   /////////////
//////////////////////////////////////////////////
Object.defineProperty(exports, "__esModule", { value: true });
exports.notificationMessages = void 0;
//////////////////////////////////////////////////
//////////////      MESSAGES LIST    /////////////
//////////////////////////////////////////////////
exports.notificationMessages = {
    "missing-email": "The request misses the email",
    "invalid-email": "The email is not valid",
    "invalid_action": "Aucune action n'a été validée .... y'a une couille dans l'pâté !",
    "dbconnect-error": "Database connection has failed",
    "maxconnect-reached": "Too many connection to the database, please try later",
    "request-failure": "The request has failed",
    "session-over": "Ton temps de connexion est écoulé, reconnecte toi (je  vais essayer d'améliorer çà)",
    "email-failure": "The email dosn't exist in the database",
    "email-success": "The email exists in the database",
    "email_bad_format": "Attention, l'adresse mail n'est pas au bon format",
    "dbconnect-success": "Connection to the database is done !",
    "missing-datas": "The request misses datas",
    "missing-results": "The request misses results",
    "delete-failure": "The deletion has failed",
    "datas-failure": "The datas are not valid",
    "move-failure": "The move has failed",
    "datas-success": "The datas are valid",
    "compare-failure": "Failure during the comparison",
    "password-failure": "The password is not valid",
    "account_not_active": "Le compte n'est pas encore activer, veuillez vérifier vos email et vos spams",
    "account_activated": "Le compte est correctement activé",
    "adduser_success": "Votre inscription sur le site GameGogs a réussi. Veuillez à présent vous connecter.",
    "certificate-failure": "The certificate is not valid",
    "certificate-success": "The certificate list ok",
    "certificate-not-found": "The certificate is not found",
    "certificate-already-exist": "Mais tu as déjà ce certificat !",
    "data_missing": "Vous devez renseigner tous les champs pour vous inscrire.",
    "dbconnect_error": "Il y a un problème pour se connecter à la base de données",
    "email_empty": "Vous devez saisir une adresse mail.",
    "exist_email": "Le mail existe déjà",
    "exist_data": "Le pseudo ou le mail existe déjà",
    "email_success": "Merci, nous avons bien enregistré votre adresse mail",
    "email_failure": "L'envoie du mail a échoué",
    "login_success": "Vous êtes à présent connecté à votre compte.",
    "login_failure": "Le mot de passe ou le pseudo n'existe pas dans la base de donnée.",
    "login_missing": "Vous devez saisir un pseudo et un mot de passe pour vous connecter.",
    "logout_success": "Vous êtes déconnecté/ A bientôt !",
    "max_connection_reached": "Le nombre maximum de connexions à la base de données a été atteint",
    "modifyuser_success": "Les données on été modifiées avec succès",
    "modifyuser_fail": "Les données n'ont pas pu être modifées",
    "password_bad_format": "Attention, le mot de passe doit contenir ces caractères [0-9], [A-Z], [a-z] et !@#$%^&*()_+{}|:;<>,.?~[-]",
    "password_failure": "Le mot de passe n'est pas bon",
    "password_verification_failed": "La vérification du mot de passe a échoué",
    "questions-success": "Les questions ont bien été récupérées",
    "questions-failure": "Les questions n'ont pas eux de réponse",
    "request_error": "La requête a échoué",
    "route_success": "L'accès à cette route est autorisé et s'est déroulé correctement",
    "signin_success": "Votre inscription sur le site ASMtariSTe a réussi. Un mail vous a été envoyé par mail, \nveuillez cliquer sur le lien d'activation pour activer votre compte.",
    "signin_failure": "L'inscription ne s'est pas déroulée correctement",
    "signout_success": "Vous êtes définitivement désinscrit du site. Vos données ont été détruites.",
    "signout_failure": "Le pseudo ou le mail n'existe pas",
    "request_success": "La requête a été effectuée avec succès",
    "invalid_id": "Aucun id n'est valide",
    "unknown_id": "identifiant inconnu",
    "token_missing": "Une erreur est survenue avec le token",
    "token_failure": "Une erreur est survenue avec le token",
    "transaction-start-failed": "La transaction n'a pas pu être démarrée",
    "test_token_failure": "le token est pas bon",
    "test_refresh_failure": "le refresh token est pas bon",
    "test_newtoken_failure": "le new token est pas bon",
    "is_not_admin": "Bienvenue Omega !",
    "is_admin": "Vous êtes l'administrateur. Accès autorisé",
    "no-questions": "Tu n'as répondu à aucune questions",
    "answers-missing": "Tu n'as pas répondu à toutes les questions",
};
